version: "3"
services:
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile.webserver
    ports:
      - "8080:5000"
    volumes:
      - ~/.aws/:/root/.aws
    depends_on:
      - kafka
      - signin

  signin:
    build:
      context: ./manageusers
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ~/.aws/:/root/.aws

  kafka:
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  prescription-analyzer:
    build:
      context: ./prescription-analyzer
      dockerfile: Dockerfile.pa
    volumes:
      - ~/.aws/:/root/.aws
    depends_on:
      - kafka
      - webserver

