FROM golang:1.19-alpine3.16

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify
# RUN apk update && apk add build-base
COPY . .
RUN go build -v -o /usr/local/bin/app ./...
CMD ["app"]