# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"c\n\x07Message\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\t\x12\x11\n\tphone_num\x18\x04 \x01(\t\x12\x11\n\tconfirmed\x18\x05 \x01(\x08\"#\n\x0fMessageResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x41\n\x0cRegistration\x12\x31\n\x11GetServerResponse\x12\x08.Message\x1a\x10.MessageResponse\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

_REGISTRATION = DESCRIPTOR.services_by_name['Registration']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=15
  _MESSAGE._serialized_end=114
  _MESSAGERESPONSE._serialized_start=116
  _MESSAGERESPONSE._serialized_end=151
  _REGISTRATION._serialized_start=153
  _REGISTRATION._serialized_end=218
# @@protoc_insertion_point(module_scope)
