# syntax=docker/dockerfile:1

FROM python:3.11.0rc2-alpine
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY app.py .
COPY templates templates
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0";"python3" "app.py"]