# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prescription-analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprescription-analyzer.proto\x12\tpanalyzer\"#\n\x0fPatientUsername\x12\x10\n\x08username\x18\x01 \x01(\t\"1\n\x0ePrescribedDrug\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\t\"E\n\x0fPrescribedDrugs\x12\x32\n\x0fprescribedDrugs\x18\x01 \x03(\x0b\x32\x19.panalyzer.PrescribedDrug2c\n\x13PrescriptioAnalyzer\x12L\n\x12getPrescribedDrugs\x12\x1a.panalyzer.PatientUsername\x1a\x1a.panalyzer.PrescribedDrugsb\x06proto3')



_PATIENTUSERNAME = DESCRIPTOR.message_types_by_name['PatientUsername']
_PRESCRIBEDDRUG = DESCRIPTOR.message_types_by_name['PrescribedDrug']
_PRESCRIBEDDRUGS = DESCRIPTOR.message_types_by_name['PrescribedDrugs']
PatientUsername = _reflection.GeneratedProtocolMessageType('PatientUsername', (_message.Message,), {
  'DESCRIPTOR' : _PATIENTUSERNAME,
  '__module__' : 'prescription_analyzer_pb2'
  # @@protoc_insertion_point(class_scope:panalyzer.PatientUsername)
  })
_sym_db.RegisterMessage(PatientUsername)

PrescribedDrug = _reflection.GeneratedProtocolMessageType('PrescribedDrug', (_message.Message,), {
  'DESCRIPTOR' : _PRESCRIBEDDRUG,
  '__module__' : 'prescription_analyzer_pb2'
  # @@protoc_insertion_point(class_scope:panalyzer.PrescribedDrug)
  })
_sym_db.RegisterMessage(PrescribedDrug)

PrescribedDrugs = _reflection.GeneratedProtocolMessageType('PrescribedDrugs', (_message.Message,), {
  'DESCRIPTOR' : _PRESCRIBEDDRUGS,
  '__module__' : 'prescription_analyzer_pb2'
  # @@protoc_insertion_point(class_scope:panalyzer.PrescribedDrugs)
  })
_sym_db.RegisterMessage(PrescribedDrugs)

_PRESCRIPTIOANALYZER = DESCRIPTOR.services_by_name['PrescriptioAnalyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PATIENTUSERNAME._serialized_start=42
  _PATIENTUSERNAME._serialized_end=77
  _PRESCRIBEDDRUG._serialized_start=79
  _PRESCRIBEDDRUG._serialized_end=128
  _PRESCRIBEDDRUGS._serialized_start=130
  _PRESCRIBEDDRUGS._serialized_end=199
  _PRESCRIPTIOANALYZER._serialized_start=201
  _PRESCRIPTIOANALYZER._serialized_end=300
# @@protoc_insertion_point(module_scope)
