# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import prescription_analyzer_pb2 as prescription__analyzer__pb2


class PrescriptioAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPrescribedDrugs = channel.unary_stream(
                '/panalyzer.PrescriptioAnalyzer/getPrescribedDrugs',
                request_serializer=prescription__analyzer__pb2.PatientUsername.SerializeToString,
                response_deserializer=prescription__analyzer__pb2.PrescribedDrug.FromString,
                )


class PrescriptioAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPrescribedDrugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrescriptioAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPrescribedDrugs': grpc.unary_stream_rpc_method_handler(
                    servicer.getPrescribedDrugs,
                    request_deserializer=prescription__analyzer__pb2.PatientUsername.FromString,
                    response_serializer=prescription__analyzer__pb2.PrescribedDrug.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'panalyzer.PrescriptioAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrescriptioAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPrescribedDrugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/panalyzer.PrescriptioAnalyzer/getPrescribedDrugs',
            prescription__analyzer__pb2.PatientUsername.SerializeToString,
            prescription__analyzer__pb2.PrescribedDrug.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
